### ISSUE TITLE
error in code @assigning batch of labels

### ISSUE THREAD

**Issue by nullmightybofo** [tuggeluk/DeepScoresExamples#1]
https://github.com/tuggeluk/DeepScoresExamples/blob/5fb6b19e014f7697cbea54f81d633f224fbbb3f1/Example_Classification.py#L127

I have the feeling that the second line here:
`x: test_images[0:FLAGS.test_batch_size]`,
`y_[0:FLAGS.test_batch_size]: test_labels`

should be changed to read like so:
`y_: test_labels[0:FLAGS.test_batch_size]`

At least, then the code in  `Example_Classification.py` runs through.

BR

**Comment by tuggeluk** [comment]
of course you are right, probably an old copy paste error.... 
thanks
L
