### ISSUE TITLE
a problem about Classification_BatchDataset.py

### ISSUE THREAD

**Issue by AaronLee150102** [tuggeluk/DeepScoresExamples#2]
There is no file named class_names.csv in the DeepScores2017_classification.zip.where can I find the suitable datasets.

**Comment by maximumspatium** [comment]
> Where can I find the suitable datasets

For classification: https://drive.google.com/file/d/1bdBrX0dAX734I3MA_6-wH_-N2eqq_tf_/view

For segmentation: https://drive.google.com/open?id=1KFxqi0rO-bJrd03rLk87fF1iOmnjpaoG

Both are accessible from the [main page](https://tuggeluk.github.io/deepscores/).

_You'll need a very powerful computer equipped with a performant GPU to train the nets. It's practically impossible to do that in a consumer-grade PC..._

**Comment by AaronLee150102** [comment]
I downloaded the data set from this site, but it was in the wrong directory format, especially for this project：https://github.com/tuggeluk/DeepWatershedDetection . I followed the dataset Settings in readme, but still could not identify the dataset.

**Comment by AaronLee150102** [comment]
The main problem is "0 roidb entrie",

**Comment by AaronLee150102** [comment]
where to find class_name.csv

**Comment by AaronLee150102** [comment]
where can I find the file named class_name.csv when I use deepscores


发自我的iPhone

------------------ Original ------------------

**Comment by maximumspatium** [comment]
> where can I find the file named class_name.csv when I use deepscores 发自我的iPhone

https://drive.google.com/file/d/1bdBrX0dAX734I3MA_6-wH_-N2eqq_tf_/view

Download and unzip.

**Comment by AaronLee150102** [comment]
Thank you very much


发自我的iPhone

------------------ Original ------------------
